### ISSUE TITLE
Change Update Now text (Localization)

### ISSUE THREAD

**Issue by navidyazdi** [jsakamoto/Toolbelt.Blazor.PWA.Updater#6]
Hi
I want to change the text of `Update Now` button. It would be nice if you use a parameter for this one as well, so we can translate it!

Thanks

**Comment by jsakamoto** [comment]
I hope the `ButtonCaption` parameter will help you. ;)

https://github.com/jsakamoto/Toolbelt.Blazor.PWA.Updater#%EF%B8%8F-configuration

**Comment by navidyazdi** [comment]
Thanks
